config/routes.rb
Rails.application.routes.draw do
  get 'grades/export' => "grades#export"
  get 'grades/stastics' => "grades#stastics"
  post 'grades/stastics' => "grades#stastics"
  post 'grades/import' => "grades#import"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homes#index'

  resources :courses do
    member do
      get :quit
      get :open
      get :close
      get :student_list
      get :course_outline
      get :course_discuss
      get :edit_outline
    end
    collection do
      get :my_course_list
      post :my_course_list
      post :save_discuss
      post :select
      get :list
      post :list
    end
  end

  resources :discusss
  resources :discussions, only: [:index, :update]
  
  
  resources :grades, only: [:index, :update]
  resources :discussions
  resources :grades, only: [:index, :update, :export, :import,:stastics]
  resources :users
  resources :notices
  
  resources :discussions do
    member do
    end
    collection do
      post :update
    end
  end
  
  resources :comments do
    member do
    end
    collection do
      get :list
    end
  end

  get 'sessions/login' => 'sessions#new'
  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  include CoursesHelper

  before_action :teacher_logged_in, only: [:update, :export, :import]

  def update
    @grade=Grade.find_by_id(params[:id])
    if @grade.update_attributes!(:grade => params[:grade][:grade])
      flash={:success => "#{@grade.user.name} #{@grade.course.name}的成绩已成功修改为 #{@grade.grade}"}
    else
      flash={:danger => "上传失败.请重试"}
    end
    redirect_to grades_path(course_id: params[:course_id]), flash: flash
  end

  def index
    if teacher_logged_in?
      @course=Course.find_by_id(params[:course_id])
      @grades=@course.grades
    elsif student_logged_in?
      @grades=current_user.grades
    else
      redirect_to root_path, flash: {:warning => "请先登陆"}
    end
  end

  def export
    course = Course.find_by_id(params[:course_id])
    respond_to do |format|
      format.xls {
        require 'tempfile'
        temp_file = Tempfile.new("#{current_user.id.to_s+'_'+course.name}.xls")

        workbook = Spreadsheet::Workbook.new
        worksheet = workbook.create_worksheet
        worksheet.row(0).concat %w{学号 姓名 专业 培养单位 邮箱 成绩}
        course.grades.each_with_index do |grade, i|
          worksheet.row(i+1).push grade.user.num, grade.user.name, grade.user.major, grade.user.department, grade.user.email, grade.grade
        end
        workbook.write temp_file
        send_file temp_file, :type => "application/vnd.ms-excel", :filename => "#{course.name}.xls", :stream => false
        # temp_file.rewind
      }
    end
  end

  def stastics
    @grades = []
    @courses= get_student_course()
    @all_semester= get_course_info(@courses, 'year', 'term_num')
    @current_semester = get_current_semester()
    semester = nil

    if request.post?
      if params[:semester] !=''
        @current_semester = params[:semester]
        semester = semester_to_array(@current_semester)
      end
    else
      semester = semester_to_array(@current_semester)
    end

    if semester
      current_user.grades.each do|grade|
        if grade.course.year == semester[0] and grade.course.term_num == semester[1]
          @grades << grade
        end
      end
    else
      @current_semester = nil
      @grades = current_user.grades
    end
    @total_score = 0
    @total_credit= 0
    @means_core = 0
    if !(@grades.nil?)
      @grade_level = {"优" => 0, "良" => 0, "中" => 0, "及格" => 0, "不及格" => 0}
      @grades.each do |grade|
        if !(grade.grade.nil?)
          @credits = grade.course.credit.split('/')
          @total_score+=grade.grade * @credits[1].to_i
          @total_credit+=@credits[1].to_f
          if grade.grade <60
            @grade_level["不及格"]+=1
          elsif grade.grade <70
            @grade_level["及格"]+=1
          elsif grade.grade <80
            @grade_level["中"]+=1
          elsif grade.grade <90
            @grade_level["良"]+=1
          else
            @grade_level["优"]+=1
          end
        end
      end
    end
  end


  def import
    file = params[:excel_file]
    course_id = params[:course_id]
    flash = {}
    if file and file.original_filename.split('.')[-1] == 'xls'
      book = Spreadsheet.open file.path
      error_student = []
      worksheet = book.worksheet 0
      worksheet.each_with_index do |row, i|
        if i != 0
          cur_student = User.find_by_num(row[0]) # row[0] is the student_num
          if not cur_student
            error_student << i + 1
            next
          end
          grade = Grade.where('course_id = ? and user_id=?', course_id, cur_student.id).take
          if not row[-1] or row[-1] < 0 or row[-1] > 100 or not grade or (not grade.update(grade: row[-1]))
            error_student << i + 1
          end
        end
      end
      flash[:success] = "上传成功,共有#{worksheet.last_row_index}个学生, #{worksheet.last_row_index - error_student.length}个学生成绩已更新"
      if error_student.length !=0
        flash[:warning] = "行号为 #{error_student.join(' , ')} 的学生更新失败，请检查学号以及分数的合法性"
      end
    else
      flash[:danger] = '文件格式错误'
    end
    redirect_to grades_path(course_id: course_id), flash: flash
  end

  private

# Confirms a teacher logged-in user.
  def teacher_logged_in
    unless teacher_logged_in?
      redirect_to root_url, flash: {danger: '请登陆'}
    end
  end

end

app/views/grades/_grade_info_visualization.html.erb
<div class="panel panel-primary filterable table_border">
  <div id="collapseGradeInfo" class="panel-collapse collapse in">
    <div class="panel-body table_border_trans">
      <div id="Grade_statistic" style="width:100%;height:400px;"></div>
    </div>
    <script type="text/javascript">
        var chart = echarts.init(document.getElementById('Grade_statistic'));

        option = {
            title: {
                text: '成绩分布信息统计',
                x: 'center'
            },
            tooltip: {
                trigger: 'item',
                formatter: "{a} <br/>{b} : {c} ({d}%)"
            },
            legend: {
                orient: 'vertical',
                left: 'left',
                data: [
                    <% @grade_level.keys.each do |key|%>
                    '<%= key %>',
                    <% end%>
                ]

            },
            series: [
                {
                    type: 'pie',
                    radius: '55%',
                    center: ['50%', '60%'],
                    data: [
                        <% @grade_level.each do |key,value|%>
                        {value:<%= value %>, name: '<%= key %>'},
                        <% end%>
                    ],
                    itemStyle: {
                        emphasis: {
                            shadowBlur: 10,
                            shadowOffsetX: 0,
                            shadowColor: 'rgba(0, 0, 0, 0.5)'
                        }
                    }
                }
            ]
        };

        chart.setOption(option);

    </script>
  </div>
</div>

app/views/grades/_grade_select_form.erb
<div class="col-sm-4" style="padding-bottom: 26px;">
  <label for="name" class="col-sm-2 control-label"><%= name %></label>
  <div class="col-sm-10">
    <select class="form-control" name="<%= submit_name %>">
      <% if nil != @current_semester %>
          <option value="<%= @current_semester %>"><%= @current_semester %></option>
      <% end %>
      <option value=""><%= submit_name == 'semester'? '所有学期':'' %></option>
      <% info.each do |info| %>
          <% if info != @current_semester %>
              <option value="<%= info %>"><%= info %></option>
          <% end %>
      <% end %>
    </select>
  </div>
</div>

app/views/grades/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-primary table_border">
        <div class="panel-heading table_new">
          <% if teacher_logged_in? %><h3 class="panel-title">成绩管理: <%= @course.name %></h3>
          <% end %>
          <% if student_logged_in? %><h3 class="panel-title">成绩列表</h3>
          <% end %>
        </div>

        <div class="panel-body" style="min-height: 450px">
          <% if teacher_logged_in? %>
              <div class="row">
                <div class="col-sm-12" style="padding-bottom: 26px">
                  <%= form_tag 'grades/import', method: "post", multipart: true, :class => "form_file" do %>
                      <div class="file_style">
                        <input type="hidden" value="<%= @course.id %>" name="course_id">
                        <input type='text' name='textfield' id='textfield' class='fileText'>
                        <input type='button' class='btn' value='浏览'>
                        <%= file_field_tag :excel_file, :class => "fileInput", :size => "28", :onchange => "document.getElementById('textfield').value=this.value" %>
                        <%= submit_tag "上传", :class => "btn" %>
                        <%= link_to "导出", grades_export_url(:course_id => @course.id, :format => 'xls'), :class => "btn" %>
                      </div>
                  <% end %>
                </div>
              </div>
          <% end %>

          <table class="table table-striped table-hover">
            <thead>
            <tr>
              <% if not student_logged_in? %>
                  <th>学号</th>
                  <th>名字</th>
                  <th>专业</th>
                  <th>培养单位</th>
              <% end %>
              <th>课程</th>
              <th>学期</th>
              <th>分数</th>
            </tr>
            </thead>
            <tbody>

            <% @grades.each do |grade| %>
                <tr>
                  <% if not student_logged_in? %>
                      <td><%= grade.user.num %></td>
                      <td><%= grade.user.name %></td>
                      <td><%= grade.user.major %></td>
                      <td><%= grade.user.department %></td>
                  <% end %>

                  <td><%= grade.course.name %></td>
                  <td><%= grade.course.year.to_s + '-' + grade.course.term_num.to_s %></td>
                  <td><%= grade.grade %></td>

                  <% if teacher_logged_in? %>
                      <%= form_for grade, url: grade_url(id: grade.id, course_id: grade.course.id), method: :patch do |f| %>
                          <td><%= f.text_field :grade %></td>
                          <td><%= f.submit "提交", class: "btn btn-success btn-xs btn_new" %></td>
                      <% end %>
                  <% end %>

                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/grades/stastics.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-primary filterable table_border">
      <div class="panel-heading table_new">
        <h3 class="panel-title">成绩统计</h3>
      </div>
      <div class="panel-body table_border">
        <div class="row">
          <%= form_tag("/grades/stastics", method: "post") do %>
              <div class="form-group">
                <%= render 'grades/grade_select_form', info: @all_semester,
                           submit_name: "semester", name: "学期" %>
              </div>
              <button type="submit" class="btn btn_new">提交</button>
          <% end %>
        </div>
      </div>

      <div class="panel panel-primary filterable table_border_trans">
        <div class="table-responsive  ">
          <table class="table table-striped" id="curriculum_table">
            <tbody class="table_new">
            <tr>
              <th class="table_new">加权平均成绩：</th>
              <% if @total_credit!=0 %>
                  <th><%= @total_score/@total_credit %></th>
              <% end %>
            </tr>
            </tbody>
          </table>
        </div>
      </div>


      <%= render 'grades/grade_info_visualization' %>
    </div>
  </div>
</div>
</div>