config/routes.rb
Rails.application.routes.draw do
  get 'grades/export' => "grades#export"
  get 'grades/stastics' => "grades#stastics"
  post 'grades/stastics' => "grades#stastics"
  post 'grades/import' => "grades#import"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homes#index'

  resources :courses do
    member do
      get :quit
      get :open
      get :close
      get :student_list
      get :course_outline
      get :course_discuss
      get :edit_outline
    end
    collection do
      get :my_course_list
      post :my_course_list
      post :save_discuss
      post :select
      get :list
      post :list
    end
  end

  resources :discusss
  resources :discussions, only: [:index, :update]
  
  
  resources :grades, only: [:index, :update]
  resources :discussions
  resources :grades, only: [:index, :update, :export, :import,:stastics]
  resources :users
  resources :notices
  
  resources :discussions do
    member do
    end
    collection do
      post :update
    end
  end
  
  resources :comments do
    member do
    end
    collection do
      get :list
    end
  end

  get 'sessions/login' => 'sessions#new'
  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base

  before_save :downcase_email
  attr_accessor :remember_token
  validates :name, presence: true, length: {maximum: 50}
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  has_many :comments
  has_many :grades
  has_many :courses, through: :grades
  has_many :courses, through: :comments
  
  has_many :teaching_courses, class_name: "Course", foreign_key: :teacher_id

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}

  #1. The ability to save a securely hashed password_digest attribute to the database
  #2. A pair of virtual attributes (password and password_confirmation), including presence validations upon object creation and a validation requiring that they match
  #3. An authenticate method that returns the user when the password is correct (and false otherwise)
  has_secure_password
  # has_secure_password automatically adds an authenticate method to the corresponding model objects.
  # This method determines if a given password is valid for a particular user by computing its digest and comparing the result to password_digest in the database.

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def user_remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def user_forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def user_authenticated?(attribute, token)
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  private

  def downcase_email
    self.email = email.downcase
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in, only: :update
  before_action :correct_user, only: [:update, :destroy]

  def new
    @user=User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, flash: {success: "新账号注册成功,请登陆"}
    else
      flash[:warning] = "账号信息填写有误,请重试"
      render 'new'
    end
  end

  def edit
    @user=User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    if @user.update_attributes(user_params)
      flash={:success => "更新成功"}
    else
      flash={:warning => "更新失败"}
    end
    redirect_to root_path, flash: flash
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
    redirect_to users_path(new: false), flash: {success: "用户删除"}
  end


#----------------------------------- students function--------------------



  private

  def user_params
    params.require(:user).permit(:name, :email, :major, :department, :password,
                                 :password_confirmation)
  end

  # Confirms a logged-in user.
  def logged_in
    unless logged_in?
      redirect_to root_url, flash: {danger: '请登陆'}
    end
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    unless current_user?(@user)
      redirect_to root_url, flash: {:warning => '此操作需要管理员身份'}
    end
  end

  # Confirms a logged-in user.
  def teacher_logged_in
    unless teacher_logged_in?
      redirect_to root_url, flash: {danger: '请登陆'}
    end
  end

end

app/views/users/_form.html.erb
<%= form_for @user, html: {class: 'form-horizontal', role: 'form'} do |f| %>
    <%= render 'shared/error_messages', :object => @user %>

    <div class="form-group">
      <%= f.label "姓名", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
          <%= f.text_field :name, class: 'form-control', placeholder: "输入真实姓名" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "用户名", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></div>
          <%= f.email_field :email, class: 'form-control', placeholder: "输入有效的邮箱" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "专业", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-home"></span></div>
          <%= f.text_field :major, class: 'form-control', placeholder: "输入专业全称" %>
        </div>
      </div>
    </div>


    <div class="form-group">
      <%= f.label "培养单位", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-home"></span></div>
          <%= f.text_field :department, class: 'form-control', placeholder: "输入培养单位全称" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "密码", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
          <%= f.password_field :password, class: 'form-control', placeholder: "输入密码" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "确认密码", class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
          <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "再次输入密码" %>
        </div>
      </div>
    </div>

    <%= f.submit '注册', class: "btn btn-primary btn-block" %>
    <%= link_to '取消', root_path, :class => "btn btn-default btn-block" %>

<% end %>

app/views/users/_login_in.html.erb
<!-- 模态框（Modal） -->
<div class="modal fade" id="login_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4><span class="glyphicon glyphicon-lock"></span> 登录</h4>
      </div>
      <div class="modal-body">
        <%= form_for(:session, url: sessions_login_path, method: :post, html: {role: 'form'}) do |f| %>
            <div class="form-group">
              <%= f.label :email, "账号密码登陆" %>
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></div>
                <%= f.email_field :email, class: 'form-control', placeholder: "输入邮箱" %>
              </div>
            </div>

            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                <%= f.password_field :password, class: 'form-control', placeholder: "输入密码" %>
              </div>
            </div>

            <div class="checkbox">
              <label><%= f.check_box :remember_me %>记住我</label>
            </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
              <%= button_tag(type: "submit", class: "btn btn-success") do %>登陆
              <% end %>
              <p style="float: left">没有账号?
                <%= link_to "注册", new_user_path %>
              </p>
        <% end %>
        </div>
        </div><!-- /.modal-content -->
  </div><!-- /.modal -->
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-sm-offset-4 col-sm-4">
    <div class="panel panel-info table_border">
      <div class="panel-heading table_new">
        <h4>编辑个人信息</h4>
      </div>
      <div class="panel-body">

        <%= form_for current_user, html: {role: 'form'} do |f| %>
            <%= render 'shared/error_messages', :object => current_user %>
            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                <%= f.text_field :name, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">

              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></div>
                <%= f.text_field :email, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-home"></span></div>
                <%= f.text_field :major, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-check"></span></div>
                <%= f.text_field :department, class: 'form-control' %>
              </div>
            </div>


            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                <%= f.password_field :password, class: 'form-control', placeholder: "输入新密码" %>
              </div>
            </div>

            <div>
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "再次输入密码" %>
              </div>
            </div>

            <br>

            <%= f.submit '更新', class: "btn btn-info btn-block btn_new" %>
            <%= link_to '取消', root_path, :class => "btn btn-default btn-block btn_new_cancel" %>

            <br>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="text-center">新用户</h3>
      </div>
      <div class="panel-body">
        <%= render "users/form" %>
      </div>
    </div>
  </div>


</div>