config/routes.rb
Rails.application.routes.draw do
  get 'grades/export' => "grades#export"
  get 'grades/stastics' => "grades#stastics"
  post 'grades/stastics' => "grades#stastics"
  post 'grades/import' => "grades#import"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homes#index'

  resources :courses do
    member do
      get :quit
      get :open
      get :close
      get :student_list
      get :course_outline
      get :course_discuss
      get :edit_outline
    end
    collection do
      get :my_course_list
      post :my_course_list
      post :save_discuss
      post :select
      get :list
      post :list
    end
  end

  resources :discusss
  resources :discussions, only: [:index, :update]
  
  
  resources :grades, only: [:index, :update]
  resources :discussions
  resources :grades, only: [:index, :update, :export, :import,:stastics]
  resources :users
  resources :notices
  
  resources :discussions do
    member do
    end
    collection do
      post :update
    end
  end
  
  resources :comments do
    member do
    end
    collection do
      get :list
    end
  end

  get 'sessions/login' => 'sessions#new'
  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  include CoursesHelper
  before_action :student_logged_in, only: [:select, :quit]
  before_action :teacher_logged_in, only: [:new, :create, :edit, :destroy, :update, :student_list]
  before_action :logged_in, only: [:index, :my_course_list]

  #-------------------------for teachers----------------------

  def new
    @course=Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      current_user.teaching_courses<<@course
      redirect_to courses_path, flash: {success: "新课程申请成功"}
    else
      flash[:warning] = "信息填写有误,请重试"
      render 'new'
    end
  end

  def edit
    @course=Course.find_by_id(params[:id])
    # @semester = @course.semester # semester_format(@course.semesters[0])
  end

  def update
    @course = Course.find_by_id(params[:id])
    puts('--------')

    if @course.update_attributes(course_params)
      flash={:success => "更新成功"}
    else
      flash={:warning => "更新失败"}
    end
    redirect_to courses_path, flash: flash
  end

  def destroy
    @course=Course.find_by_id(params[:id])
    current_user.teaching_courses.delete(@course)
    @course.destroy
    flash={:success => "成功删除课程: #{@course.name}"}
    redirect_to courses_path, flash: flash
  end

  def open
    @course = Course.find_by_id(params[:id])
    @course.open = true
    if @course.save
      flash={:success => "已经成功关闭该课程:#{ @course.name}"}
    else
      flash={:warning => "开启失败"}
    end
    redirect_to courses_path, flash: flash
  end

  def close
    @course = Course.find_by_id(params[:id])
    @course.open = false
    if @course.save
      flash={:success => "已经成功关闭该课程:#{ @course.name}"}
    else
      flash={:warning => "关闭失败"}
    end
    redirect_to courses_path, flash: flash
  end


  def student_list
    @course = Course.find_by_id(params[:id])
    @user = @course.users
    @user_department = {}
    @user.each do |user|
      if !@user_department.has_key?(user.department)
        @user_department[user.department] =0
      end
      @user_department[user.department] += 1
    end
  end

  #-------------------------for students----------------------

  def list # course to select list
    @in_course_select_time = in_course_select_time?()
    if @in_course_select_time # 选课时间判断
      @course_to_choose=get_course_to_choose_list()
      @current_semester = get_current_semester()

      @course = get_current_semester_course()
      @course_time_table = get_course_table(@course)

      @course_time = get_course_info(@course_to_choose, 'course_time')
      @course_exam_type = get_course_info(@course_to_choose, 'exam_type')
      # @course_teacher = get_course_info(@course_to_choose, 'teacher')
      if request.post?
        @course_to_choose=course_filter_by_condition(@course_to_choose, params, ['course_time', 'exam_type'])
      end
    end
  end


  def select
    @in_course_select_time = in_course_select_time?()
    flash = nil
    if @in_course_select_time # 选课时间判断
      ids = params[:course_to_choose]
      if ids
        @course = Course.find(ids)
        if course_conflict?(get_current_semester_course(), @course)
          flash={:warning => "课程冲突"}
        else
          fails_course = []
          success_course = []
          @course.each do |course|
            if course.grades.length < course.limit_num and Grade.create(:user_id => current_user.id, :course_id => course.id)
              success_course << course.name
            else
              fails_course << course.name
            end
          end
          if success_course.length !=0
            flash = {:success => ("成功选择课程:  " + success_course.join(','))}
          end
          if fails_course.length !=0
            waring_info = fails_course.join(',') +'  人数已满'
            if flash != nil
              flash[:warning] = waring_info
            else
              flash = {:warning => waring_info}
            end
          end
        end
      else
        flash={:success => "请勾选课程"}
      end
    else
      flash={:warning => "不在选课时间！"}
    end
    redirect_to courses_path, flash: flash
  end


  def quit
    @course=Course.find_by_id(params[:id])
    Grade.where(:user_id => current_user.id, :course_id => @course.id).take.destroy()
    flash={:success => "成功退选课程: #{@course.name}"}
    redirect_to courses_path, flash: flash
  end


  #-------------------------for both teachers and students----------------------

  def edit_outline
    @course=Course.find_by_id(params[:id])
    # @semester = @course.semester # semester_format(@course.semesters[0])
  end

  def course_outline
    puts("this is course_outline")
    @course = Course.find_by_id(params[:id])
    @coursetmp = current_user.teaching_courses if teacher_logged_in?
  end


  def save_discuss
    @course = Course.find_by_id(params[:id])
    if @course.diss="暂无人发言"
      @course.diss=""
    end
    if @course.tmp!=nil
      @course.diss+="匿名用户："
      @course.diss+=@course.tmp
    end

    if @course.save
      flash={:success => "已经成功保存在《#{@course.name}》中的发言:#{ @course.tmp}"}
    else
      flash={:warning => "保存失败"}
    end

    redirect_to courses_path, flash: flash
  end


  def course_discuss
    @course = Course.find_by_id(params[:id])
    @test=""
  end


  def index
    redirect_to '/courses/my_course_list'
  end

  def my_course_list
    @course=current_user.teaching_courses if teacher_logged_in?
    @course= get_student_course() if student_logged_in?
    @all_semester= get_course_info(@course, 'year', 'term_num')
    @current_semester = get_current_semester()
    semester = nil
    if request.post?
      if params[:semester] !=''
        @current_semester = params[:semester]
        semester = semester_to_array(@current_semester)
      end
    else
      semester = semester_to_array(@current_semester)
    end
    if semester
      @course= filter_course_by_semester(@course, semester)
    else
      @current_semester = nil
    end
    @course_time_table = get_course_table(@course)

  end

  private
  # Confirms a student logged-in user.
  def student_logged_in
    unless student_logged_in?
      redirect_to root_url, flash: {danger: '请登陆'}
    end
  end

  # Confirms a teacher logged-in user.
  def teacher_logged_in
    unless teacher_logged_in?
      redirect_to root_url, flash: {danger: '请登陆'}
    end
  end

  # Confirms a  logged-in user.
  def logged_in
    unless logged_in?
      redirect_to root_url, flash: {danger: '请登陆'}
    end
  end

  def course_params
    params.require(:course).permit(:course_code, :name, :course_type, :teaching_type, :exam_type,
                                   :credit, :limit_num, :class_room, :course_time, :course_week,
                                   :tmp, :outline, :diss, :discussion, :discussions, :discuss,
                                   :discussess, :year, :term_num)
  end
end

app/helpers/courses_helper.rb
require 'set'

module CoursesHelper
  def semester_to_season(semester) # '2016-1'
    if semester.nil?
      return nil
    end
    semester = semester.split('-')
    if semester[1] == '1'
      semester[1] = '秋季学期'
    elsif semester[1] == '2'
      semester[1] = '春季学期'
    else
      semester[1] = '夏季学期'
    end
    semester[0] += '-' +(semester[0].to_i + 1).to_s
    semester.join('学年')
  end


  def week_data_to_num(week_data)
    param = {
        '周一' => 0,
        '周二' => 1,
        '周三' => 2,
        '周四' => 3,
        '周五' => 4,
        '周六' => 5,
        '周天' => 6,
    }
    param[week_data] + 1
  end


  def get_course_table(courses)
    course_time = Array.new(11) { Array.new(7, {'name' => '', 'id' => ''}) }
    if courses
      courses.each do |cur|
        cur_time = String(cur.course_time)
        end_j = cur_time.index('(')
        j = week_data_to_num(cur_time[0...end_j])
        t = cur_time[end_j + 1...cur_time.index(')')].split("-")
        for i in (t[0].to_i..t[1].to_i).each
          course_time[(i-1)*7/7][j-1] = {
              'name' => cur.name,
              'id' => cur.id
          }
        end
      end
    end
    course_time
  end

  def course_conflict?(current_courses, to_select_courses)
    current_course_table = get_course_table(current_courses)
    to_choose_table = get_course_table(to_select_courses)
    for i in (0...current_course_table.length)
      for j in (0...current_course_table[i].length)
        if current_course_table[i][j]['id'] != '' and to_choose_table[i][j]['id'] != ''
          return true
        end
      end
    end
    false
  end

  def get_course_info(courses, type, type2=nil)
    res = Set.new
    courses.each do |course|
      if type2
        res.add(course[type].to_s+'-'+course[type2].to_s)
      else
        res.add(course[type])
      end
    end
    res.to_a.sort
  end

  def get_student_course()
    course = []
    current_user.grades.each do |x|
      course << x.course
    end
    course
  end

  def get_current_semester()
    current_semester = Systeminfo.where(name: 'current_semester').take
    current_semester[:value]
  end

  def semester_to_array(current_semester)
    current_semester = current_semester.split('-')
    current_semester[0], current_semester[1] = current_semester[0].to_i, current_semester[1].to_i
    current_semester
  end

  def filter_course_by_semester(course, semester=nil)
    if semester == nil
      semester = semester_to_array(get_current_semester())
    end
    condition = {
        'year' => semester[0],
        'term_num' => semester[1]
    }
    course_filter_by_condition(course, condition, ['year', 'term_num'])
  end

  def get_current_semester_course()
    logged_in? ? filter_course_by_semester(get_student_course()) : nil
  end

  def course_filter_by_condition(courses, params, keys)
    if params == nil
      return courses
    end
    res = []
    courses.each do |course|
      ok = true
      keys.each do |key|
        if not (params[key] == '' or course[key] == params[key])
          ok = false
          break
        end
      end
      if ok
        res << course
      end
    end
    res
  end

  def get_course_to_choose_list()
    current_semester = semester_to_array(get_current_semester())
    course = Course.where('open = true and year=? and term_num =?',
                          current_semester[0], current_semester[1])
    logged_in? ? course- get_student_course() : course
  end

  def get_course_select_end_time()
    end_time = Systeminfo.where(name: 'course_select_end_time').take
    Time.new(*end_time[:value].split('-'))
  end

  def in_course_select_time?()
    cur_time = Time.now
    course_select_time = get_course_select_end_time()
    in_course_select_time = cur_time <= course_select_time
  end


  def semester_format(semester)
    year = semester.year
    num = semester.num
    "#{year}年第(#{num})学期"
  end
end

app/views/courses/_course_list.html.erb
<%= form_tag("/courses/select", method: "post") do %>

    <table class="table table-striped table-hover table_border">
      <thead>
      <tr>
        <% if logged_in? %>
            <th></th>
        <% end %>
        <th>课程编号</th>
        <th>课程名称</th>
        <th>课时/学分</th>
        <th>限选</th>
        <th>已选</th>
        <th>课程属性</th>
        <th>授课方式</th>
        <th>考试方式</th>
        <th>主讲教师</th>
        <th>上课时间</th>
      </tr>
      </thead>
      <tbody>
      <% @course_to_choose.each do |course_to_choose| %>   <!-- #双||表示内部的局部变量 -->
          <tr>
            <% if student_logged_in? %>
                <td><%= check_box_tag 'course_to_choose[]', course_to_choose.id, false, 'alt' =>
                    course_to_choose.id.to_s + '|'+course_to_choose.name + '|'+ course_to_choose.course_time %></td>
            <% end %>

            <td><%= course_to_choose.course_code %></td>
            <td><%= link_to course_to_choose.name, course_outline_course_url(course_to_choose) %></td>
            <td><%= course_to_choose.credit %></td>
            <td><%= course_to_choose.limit_num %></td>
            <td><%= course_to_choose.users.size %></td>
            <td><%= course_to_choose.course_type %></td>
            <td><%= course_to_choose.teaching_type %></td>
            <td><%= course_to_choose.exam_type %></td>
            <td><%= course_to_choose.teacher.name %></td>
            <td><%= course_to_choose.course_time %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <% if student_logged_in? %>
        <button type="submit" class="btn btn_new">提交</button>
    <% end %>
<% end %>

app/views/courses/_curriculum_table.html.erb
<div id="side_course_table" class="side_course_table col-sm-8">
  <div class="sideDiv_content">
    <div class="panel panel-primary filterable">
      <div class="panel-heading">
        <%= current_user.name %> <%= semester_to_season(@current_semester) %> 课程表
      </div>
      <div class="table-responsive">
        <table class="table table-bordered" id="curriculum_table" style="text-align: center">
          <thead>
          <td></td>
          <td>星期一</td>
          <td>星期二</td>
          <td>星期三</td>
          <td>星期四</td>
          <td>星期五</td>
          <td>星期六</td>
          <td>星期天</td>
          </thead>
          <tbody>
          <% (0...@course_time_table.length).each do |i| %>
              <tr>
                <td><%= i+1 %></td>
                <% (0...@course_time_table[i].length).each do |j| %>
                    <td class='row<%= i+1 %> col<%= j+1 %>' alt="<%= @course_time_table[i][j]['id'] %>">
                      <%= @course_time_table[i][j]['name'] %></td>
                <% end %>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>

  </div>
  <div class="side_course_table_ctrlBlock">
    <div id="course_table_slide_in_button" data-placement="left" class="tooltip-show" data-toggle="tooltip" title="课程表"></div>
  </div>
</div>

<script>
    function hidden_border() {
        var m = 11, n = 7;
        for (var j = 1; j <= n; j++) {
            for (var i = m; i >= 0; i--) {
                var cur = $('.row' + i + '.col' + j);
                if (i - 1 >= 0 && cur.attr('alt') != '') {
                    var pre_row = $('.row' + (i - 1) + '.col' + j);
                    if (pre_row.attr('alt') == cur.attr('alt')) {
                        pre_row.css("border-bottom", "none");
                        cur.css("border-top", "none");
                        cur.text("");
                        i--;
                        if (i - 1 <= m) {
                            var p_pre_row = $('.row' + (i - 1) + '.col' + j);
                            if (p_pre_row.attr('alt') == pre_row.attr('alt')) {
                                i--;
                                p_pre_row.css("border-bottom", "none");
                                pre_row.css("border-top", "none");
                                p_pre_row.text("");
                            }
                        }
                    }

                }
            }
        }
    }
    $(hidden_border());

    $(document).ready(
        function () {
            var sideDiv_right = $("#side_course_table").width() - 40 + (document.body.clientHeight > $(window).height() ? 16 : 25);
            var speed = 300;

            $("#side_course_table").css("right", -sideDiv_right);
            $("#side_course_table").css("top", window.pageYOffset + 100 + 'px');

            var cnt = 0;

            $("#course_table_slide_in_button").click(function () {
                if (!cnt) {
                    $("#side_course_table")
                        .animate({
                                right: '0px'
                            },
                            speed,
                            function () {
                                document.getElementById("course_table_slide_in_button").style.transform = "rotate(180deg)";
                                cnt = 1;
                            });
                } else {
                    $("#side_course_table")
                        .animate({
                                right: -sideDiv_right +'px'
                            },
                            speed,
                            function () {
                                document.getElementById("course_table_slide_in_button").style.transform = "rotate(0deg)";
                                cnt = 0;
                            });
                }
            });

        }).scroll(function () {
        $("#side_course_table").css("top", window.pageYOffset + 100 + 'px');
    });
    $(function () {
        $('.tooltip-show').tooltip('show');
    });

</script>

app/views/courses/_search_course_select_form.erb
<div class="col-sm-4" style="padding-bottom: 26px;">
  <label for="name" class="col-sm-4 control-label"><%= name %></label>
  <div class="col-sm-8">
    <select class="form-control" name="<%= submit_name %>">
      <% submit_name == 'semester' and if nil != @current_semester %>
          <option value="<%= @current_semester %>"><%= semester_to_season(@current_semester) %></option>
      <% end %>
      <option value=""><%= submit_name == 'semester' ? '所有学期' : '' %></option>
      <% info.each do |info| %>
          <% if info != @current_semester %>
              <option value="<%= info %>"><%= submit_name == 'semester' ? semester_to_season(info) : info %></option>
          <% end %>
      <% end %>
    </select>
  </div>
</div>

app/views/courses/_student_info_visualization.html.erb
<div class="panel panel-primary filterable table_border_blue">
  <div class="panel-heading table_new_blue">
    <h4 class="panel-title">
      <a data-toggle="collapse" data-parent="#accordion"
         href="#collapseStudentInfo">
        <%= @course.name %> 学生信息统计
      </a>
    </h4>
  </div>
  <div id="collapseStudentInfo" class="panel-collapse collapse in">
    <div class="panel-body">
      <div id="department_statistic" style="width:100%;height:400px;"></div>
    </div>
    <script type="text/javascript">
        var chart = echarts.init(document.getElementById('department_statistic'));

        option = {
            title: {
                text: '研究所信息统计',
                x: 'center'
            },
            tooltip: {
                trigger: 'item',
                formatter: "{a} <br/>{b} : {c} ({d}%)"
            },
            legend: {
                orient: 'vertical',
                left: 'left',
                data: [
                    <% @user_department.keys.each do |key|%>
                    '<%= key %>',
                    <% end%>
                ]

            },
            series: [
                {
                    type: 'pie',
                    radius: '55%',
                    center: ['50%', '60%'],
                    data: [
                        <% @user_department.each do |key,value|%>
                        {value:<%= value %>, name: '<%= key %>'},
                        <% end%>
                    ],
                    itemStyle: {
                        emphasis: {
                            shadowBlur: 10,
                            shadowOffsetX: 0,
                            shadowColor: 'rgba(0, 0, 0, 0.5)'
                        }
                    }
                }
            ]
        };

        chart.setOption(option);

    </script>
  </div>
</div>

app/views/courses/course_discuss.html.erb
 <style type="text/css">
			#container{
				padding-top: 10px;
			}
			
			h1{
				font-size: 28px;
				margin: 50px;
			}
			
			/* bubble */
			.tip-bubble {
			  position: relative;
			  background-color: #436EEE;
			  width: 500px;
			  padding: 20px;
			  color: #080808;
			  text-align: left;
			  border-radius: 10px;
			  margin: 50px;
			}
			 .tip-bubble:after {
			  content: '';
			  position: absolute;
			  width: 0;
			  height: 0;
			  border: 15px solid;
			}
			 
			.tip-bubble-left:after {
			  border-right-color: #202020;
			  top: 50%;
			  right: 100%;
			  margin-top: -15px;
			}
		
        </style>
 
  <div class="container-fluid">
  <div class="row">
    <div class="col-sm-12" style="text-align:center;">
      <div class="panel panel-primary filterable table_border">
        <div class="panel-heading table_new">
          <h3 class="panel-title">
              《<%= @course.name %>》Discuss区
          </h3>
        </div>
        
        <div id="button-edit">
          
       
 <div class="panel-body" style="text-align:left;">
   <div id="container">
     
            <div class="table-responsive">
          <tbody>
             <%if @course.diss == "" %>
                 <td><B>暂时无人发言！</B></td>
             <% end %>
             <% @test = @course.diss.split("匿名用户：")%>
              <% @judge ="" %>
              <% @test.each do |test| %>
                <% if test!="暂无人发言" and test != "" %>
                  <% if @judge.include? test   %>
                  <% else %>
                     	<div class="tip-bubble tip-bubble-left">
                      <td><B>匿名用户：</B></td
                      
                      <td><%= test%></td>
                       </div>
                            
                      <% @judge+=test %>
                  <% end %>
              <% end %>
             <% end %>
             
    
          </tbody>
            </div>
          </div>


 <%= render 'shared/error_messages', :object => @course %>
 
 <%#= form_for  @course, url: save_discuss_courses_path(id: @course.id), html: {class: "nifty_form"} do |f| %>
 <%#= form_for @course, html: {class: 'form-horizontal', role: 'form'} do |f| %>
 
 <%#= form_tag(@course, "/courses/save_discuss", method: "post") do %>

<%# form_for @course, :url => { :action => :save_discuss } do |f| %>

  <%=form_tag :action => "save_discuss", :id=> @course.id do %>
  <%#= text_area :@test, class: 'form-control', placeholder: "输入发言内容" %>
  <%= text_area(:course, :tmp, cols:20, row: 30) %>
  <!--<textarea name="course[tmp]" id="course_tmp" class="form-control">
  <%#=@course.tmp %>
  </textarea> -->
  <button type="submit" class="btn btn-default">提交</button>
  <% end %>
 

<!--  

   <%#= form_for @course, html: {class: 'form-horizontal', role: 'form'} do |f| %>
      <div class="col-sm-9">
        <div class="input-group input-group-lg">
          <div class="input-group-addon"><span class="glyphicon glyphicon-arrow-right"></span></div>
          <%#= f.text_area :tmp, class: 'form-control', placeholder: "输入发言内容" %>
        </div>

    <%#= f.submit '提交', class: "btn btn-success btn-block btn_new" %>
    <%#= link_to '取消', courses_path, :class => "btn btn-default btn-block" %>

  
<%# end %>

        </div>
      </div>
      
-->      
    </div>
  </div>
</div>

app/views/courses/course_outline.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6" style="text-align:center;">
      <div class="panel panel-primary filterable table_border">
        <div class="panel-heading table_new">
          <h3 class="panel-title">
            <% @coursetmp=current_user.teaching_courses if teacher_logged_in? %>
            《<%= @course.name %>》课程大纲
          </h3>
        </div>
        </br>
        <div id="button-edit">
          <!--显示评论-->
          <div class="panel-body">
            <div class="table-responsive">
              <%= @course.outline %>
            </div>
          </div>
          <!--按钮-->
          <% if teacher_logged_in? %>
              <% @coursetmp.each do |coursetmp| %>
                  <% if @course == coursetmp %>

                      <a><%= link_to "点击修改课程大纲", edit_outline_course_url(@course), class: 'btn btn-xs btn-info btn_new_cancel' %></a>
                  <% end %>
              <% end %>
          <% end %>
          <a><%= link_to "查看课程悄悄话", discussions_path(course_id: @course.id), class: 'btn btn-xs btn-info btn_new' %></a>
          <!--保证格式-->
          <div class="panel-body">
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/courses/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-offset-3 col-sm-6">
      <div class="panel panel-success table_border">
        <div class="panel-heading table_new">
          <h5 class="text-center">更改课程: <%= @course.name %></h5>
        </div>
        <div class="panel-body">
          <%= render 'courses/form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/courses/my_course_list.html.erb
<div class="container-fluid ">
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-primary filterable table_border">
        <div class="panel-heading table_new">
          <% if teacher_logged_in? %><h3 class="panel-title">授课列表</h3>
          <% end %>
          <% if student_logged_in? %><h3 class="panel-title">已选课程</h3>
          <% end %>
        </div>


        <div class="panel-body">
          <div class="row">
            <%= form_tag("/courses/my_course_list", method: "post") do %>
                <div class="form-group">
                  <%= render 'courses/search_course_select_form', info: @all_semester,
                             submit_name: "semester", name: "学期" %>
                </div>
                <button type="submit" class="btn btn-default">提交</button>
            <% end %>
          </div>

          <table class="table table-responsive table-condensed table-hover">
            <thead>
            <tr>
              <th>课程编号</th>
              <th>课程名称</th>
              <th>课时/学分</th>
              <% if teacher_logged_in? %>
                  <th>限选人数</th>
                  <th>已选人数</th>
              <% end %>
              <th>考试方式</th>
              <th>主讲教师</th>
              <th>上课时间</th>
            </tr>

            <tbody>
            <% @course.each do |course| %>
                <tr>
                  <td><%= course.course_code %></td>
                  <!-- <td><%= course.name %></td>-->
                  <td><%= link_to course.name, course_outline_course_url(course) %>

                  <td><%= course.credit %></td>
                  <% if teacher_logged_in? %>
                      <td><%= course.limit_num %></td>
                      <td><%= course.users.size %></td>
                  <% end %>
                  <td><%= course.exam_type %></td>
                  <td><%= course.teacher.name %></td>
                  <td><%= course.course_time %></td>
                  <td>
                    <% if teacher_logged_in? %>
                        <%= link_to "学生信息", student_list_course_url(course) %>
                    <% end %>
                  </td>
                  <td>
                    <% if teacher_logged_in? %>
                        <%= link_to "编辑", edit_course_url(course), class: 'btn btn-xs btn-info btn_new' %>
                        <% if course.open %>
                            <%= link_to "关闭", close_course_url(course), class: 'btn btn-xs btn-warning btn_new_close' %>
                        <% else %>
                            <%= link_to "开课", open_course_url(course), class: 'btn btn-xs btn-success' %>
                        <% end %>
                        <%= link_to "删除", course_path(course), :method => "delete", class: 'btn btn-xs btn-danger btn_new_del', :data => {confirm: '确定要删除此课程?'} %>
                    <% elsif student_logged_in? %>
                        <%= link_to "退课", quit_course_path(course), class: 'btn-sm btn-danger btn_new' %>
                    <% end %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>


    </div>
  </div>
</div>
<%= render 'courses/curriculum_table' %>

app/views/courses/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-offset-2 col-sm-8">
      <div class="panel panel-success">
        <div class="panel-heading table_new">
          <h3 class="text-center">新课程</h3>
        </div>
        <div class="panel-body">
          <%= render "courses/form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/courses/student_list.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-primary filterable table_border">
        <div class="panel-heading table_new">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion"
               href="#collapseStudentList">
              <%= @course.name %> 选课名单
            </a>
          </h4>
        </div>
        <div id="collapseStudentList" class="panel-collapse collapse in">
          <div class="panel-body">

            <div class="row">
              <div class="col-sm-12" style="padding-bottom: 26px;">
               <%= link_to "导出", grades_export_url(:course_id =>@course.id,:format => 'xls'),:class =>"btn btn-info btn_new"%>
              </div>
            </div>

            <div class="table-responsive">
              <table class="table table-striped table-hover">
                <thead>
                <tr>
                  <th>学号</th>
                  <th>名字</th>
                  <th>专业</th>
                  <th>培养单位</th>
                  <th>电子邮件</th>
                </tr>
                </thead>
                <tbody>

                <% @user.each do |user| %>
                    <tr>
                      <td><%= user.num %></td>
                      <td><%= user.name %></td>
                      <td><%= user.major %></td>
                      <td><%= user.department %></td>
                      <td><%= user.email %></td>
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <%= render 'courses/student_info_visualization' %>
    </div>
  </div>
</div>