config/routes.rb
Rails.application.routes.draw do
  get 'grades/export' => "grades#export"
  get 'grades/stastics' => "grades#stastics"
  post 'grades/stastics' => "grades#stastics"
  post 'grades/import' => "grades#import"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homes#index'

  resources :courses do
    member do
      get :quit
      get :open
      get :close
      get :student_list
      get :course_outline
      get :course_discuss
      get :edit_outline
    end
    collection do
      get :my_course_list
      post :my_course_list
      post :save_discuss
      post :select
      get :list
      post :list
    end
  end

  resources :discusss
  resources :discussions, only: [:index, :update]
  
  
  resources :grades, only: [:index, :update]
  resources :discussions
  resources :grades, only: [:index, :update, :export, :import,:stastics]
  resources :users
  resources :notices
  
  resources :discussions do
    member do
    end
    collection do
      post :update
    end
  end
  
  resources :comments do
    member do
    end
    collection do
      get :list
    end
  end

  get 'sessions/login' => 'sessions#new'
  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

end

app/views/layouts/_content.html.erb
<br>
<div class="container">

  <% flash.each do |message_type, message| %>
      <% if params[:controller] !="homes" %>
          <div class="alert alert-<%= message_type %>">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong> <%= message %></strong>
          </div>
      <% else %>
          <script>alert("<%= message %>");</script>
      <% end %>
  <% end %>
</div>

<div class="container" style="min-height:470px" id="main_container">
  <%= yield %>
</div>

app/views/layouts/_footer.html.erb
<footer class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="col-sm-2">
          <img src="/images/ucas_logo.png" alt="ucas_logo">
        </div>
        <div class="col-sm-offset-1 col-sm-5">
          <p>中国科学院大学版权所有 © 2019<br></p>
          <p> 地址：北京市雁西湖校区 </p>
        </div>
        <div class="col-sm-offset-1  col-sm-3">
          <p><span class="glyphicon glyphicon-chevron-right">
          <%= link_to '中国科学院大学', 'http://www.gucas.ac.cn/' %>
          </span></p>

          <p><span class="glyphicon glyphicon-chevron-right">
          <%= link_to '中国科学院大学图书馆', 'http://lib.ucas.ac.cn/home' %>
          </span></p>
        </div>
      </div>

    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<%= javascript_include_tag('echarts.min.js') %>
<%= javascript_include_tag('modernizr.custom.js') %>
<%= javascript_include_tag('classie.js') %>
<%= javascript_include_tag('gnmenu.js') %>
<%= javascript_include_tag('d3.v3.min.js') %>


<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">


    <!--新添加的按钮，可以有侧边bar-->
    <ul id="gn-menu" class="gn-menu-main">
      <li class="gn-trigger">
        <a class="gn-icon gn-icon-menu"></a>
        <nav class="gn-menu-wrapper">
          <div class="gn-scroller">
            <ul class="gn-menu">

              <% if logged_in? %>
                  <!--1. 教师：课程管理 & 学生：选修课程-->
                  <li>
                    <a><span class="glyphicon glyphicon-th-list"> </span>
                      <%= teacher_logged_in? ? "课程管理" : "选修课程" %></a>

                    <ul class="gn-submenu">
                      <!--教师登陆：课程管理-已授课程／创建新课程-->
                      <% if teacher_logged_in? %>
                          <li>
                            <%= link_to courses_path do %>
                                <span class="glyphicon glyphicon-hand-right"></span>已授课程
                                <span class="label label-info pull-right"><%= current_user.teaching_courses.length %></span>
                            <% end %>
                          </li>
                          <li>
                            <%= link_to new_course_path do %>
                                <span class="glyphicon glyphicon-hand-right"></span>创建新课程
                            <% end %>
                          </li>
                      <% end %>


                      <!--学生登陆：选修课程-选修课程／已选课程-->
                      <% if student_logged_in? %>
                          <li>
                            <%= link_to list_courses_path do %>
                                <span class="glyphicon glyphicon-hand-right"></span> 选修课程
                                <span class="label label-info pull-right"> <%= get_course_to_choose_list().length %></span>
                            <% end %>
                          </li>
                          <li>
                            <%= link_to courses_path do %>
                                <span class="glyphicon glyphicon-hand-right"></span> 已选课程
                                <span class="label label-info pull-right"><%= current_user.courses.length %></span>
                            <% end %>
                          </li>
                      <% end %>
                    </ul>
                  </li>

                  <!--2. 教师：成绩管理 & 学生：所有成绩-->
                  <li>
                    <a><span class="glyphicon glyphicon-export"> </span>
                      <%= teacher_logged_in? ? "成绩管理" : "所有成绩" %></a>

                    <ul class="gn-submenu">
                      <!--2'. 教师 & 学生：所有课程显示-->
                      <% if teacher_logged_in? %>
                          <% current_user.teaching_courses.each do |course| %>
                              <li>
                                <%= link_to grades_path(course_id: course.id), :method => :get do %>
                                    <span class="glyphicon glyphicon-hand-right"></span> <%= course.name %>
                                    <span class="label label-info pull-right"><%= course.users.length %></span>
                                <% end %>
                              </li>
                          <% end %>
                      <% end %>

                      <% if student_logged_in? %>
                          <li>
                            <%= link_to grades_path do %>
                                <span class="glyphicon glyphicon-hand-right"></span> 所有成绩
                            <% end %>
                          </li>
                          <li>
                            <%= link_to grades_stastics_path do %>
                                <span class="glyphicon glyphicon-hand-right"></span> 成绩统计
                            <% end %>
                          </li>
                      <% end %>
                    </ul>
                  </li>
                  <!--3. 教师：评估结果 & 学生：课程评估-->
                  <li>
                    <a><span class="glyphicon glyphicon-star"> </span>
                      <%= teacher_logged_in? ? "评估结果" : "评估课程" %></a>

                    <ul class="gn-submenu ">
                      <% if teacher_logged_in? %>
                          <% current_user.teaching_courses.each do |course| %>
                              <li>
                                <%= link_to list_comments_path(course_id: course.id), :method => :get do %>
                                    <span class="glyphicon glyphicon-hand-right"></span> <%= course.name %>
                                    <span class="label label-info pull-right"><%= course.users.length %></span>
                                <% end %>
                              </li>
                          <% end %>
                      <% end %>

                      <% if student_logged_in? %>
                          <li>
                            <%= link_to comments_path do %>
                                <span class="glyphicon glyphicon-hand-right"></span> 评估课程
                            <% end %>
                          </li>
                      <% end %>
                    </ul>
                  </li>
              <% end %>
            </ul>
          </div><!-- /gn-scroller -->
        </nav>
      </li>
      <li></li>
    </ul>

    <div style="position: relative">
      <div class="navbar-header">
        <%= link_to "CourseSelect", root_path, class: 'navbar-brand font_size' %>
      </div>

      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">

          <li class="<%= "active " if params[:controller]=="homes" %>"> <%= link_to "主页", root_path %></li>

          <% if student_logged_in? %>
              <li class=<%= "active change_bg_font" if params[:controller]=="courses" and not current_page?(list_courses_path) %>> <%= link_to "我的课程", courses_path %></li>
          <% elsif teacher_logged_in? %>
              <li class=<%= "active change_bg_font" if params[:controller]=="courses" and not current_page?(list_courses_path) %>> <%= link_to "课程管理", courses_path %></li>
          <% elsif admin_logged_in? %>
              <li> <%= link_to "控制面板", rails_admin_path %></li>
          <% end %>
          <li class=<%= "active change_bg_font" if current_page?(list_courses_path) %>> <%= link_to  student_logged_in?? "选修课程":"已开放的课程列表", list_courses_path %></li>
          <li class="<%= "active " if params[:controller]=="notices" %>"> <%= link_to "通知", '/notices/' %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">

          <% if current_user %>
              <li>
                <%= link_to edit_user_path(current_user) do %>
                    <%= current_user.name %><span class="glyphicon glyphicon-user"></span>
                <% end %>
              </li>

              <li>
                <p class="navbar-text"><%= current_user.department %></p>
              </li>

              <li>
                <%= link_to sessions_logout_path, method: :delete do %>
                    退出 <span class="	glyphicon glyphicon-off"></span>
                <% end %>
              </li>

          <% else %>
              <li><a data-toggle="modal" data-target="#login_modal">
                登录 <span class="	glyphicon glyphicon-user"></span>
              </a>
              </li>

              <li><%= link_to new_user_path do %>
                    注册 <span class="	glyphicon glyphicon-log-in"></span>
                <% end %>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

<script> doc = new gnMenu(document.getElementById('gn-menu'));</script>

<% if not current_user %>
    <div class="modal fade" id="login_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4><span class="glyphicon glyphicon-lock"></span> 登录</h4>
          </div>
          <div class="modal-body">
            <%= form_for(:session, url: sessions_login_url, method: :post, html: {role: 'form', :id => 'login'}) do |f| %>
                <div class="form-group">
                  <%= f.label :email, "账号密码登陆" %>
                  <div class="input-group">
                    <div class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></div>
                    <%= f.email_field :email, class: 'form-control', placeholder: "输入邮箱" %>
                  </div>
                </div>

                <div class="form-group">
                  <div class="input-group">
                    <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                    <%= f.password_field :password, class: 'form-control', placeholder: "输入密码" %>
                  </div>
                </div>

                <div class="checkbox">
                  <label><%= f.check_box :remember_me %>记住我</label>
                </div>
                </div>
            <% end %>

            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
              <button type="button" class="btn btn-success" onclick="document.getElementById('login').submit()">
                登陆</button>
<p style="float: left">没有账号?
  <%= link_to "注册", new_user_path %>
</p>
</div>
</div><!-- /.modal-content -->
</div><!-- /.modal -->
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CourseSelect</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.png' %>
  <meta>
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= csrf_meta_tags %>
</head>

<body class="<%= "body_background" if params[:controller]!="homes" %>">

<%= render partial: 'layouts/header' %>
<%= render partial: 'layouts/content' %>
<%= render partial: 'layouts/footer' %>

</body>
</html>